### ISSUE TITLE
Node Fetch 3

### ISSUE THREAD

**Issue by keesvanbemmel** [GarbageSlave/afas-connect#16]
Anyone else having problems using the latest version of this module? It seems like the node-fetch version has been increased, but now my project won't build resulting in:
```
/Users/user/afas-connect-test/node_modules/afas-connect/lib/classes/Connector.js:12
const node_fetch_1 = require("node-fetch");
                     ^
 
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/user/afas-connect-test/node_modules/node-fetch/src/index.js from /Users/user/afas-connect-test/node_modules/afas-connect/lib/classes/Connector.js not supported.
Instead change the require of index.js in /Users/user/afas-connect-test/node_modules/afas-connect/lib/classes/Connector.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/user/afas-connect-test/node_modules/afas-connect/lib/classes/Connector.js:12:22)
    at Object.<anonymous> (/Users/user/afas-connect-test/node_modules/afas-connect/lib/classes/GetConnector.js:13:21)
    at Object.<anonymous> (/Users/user/afas-connect-test/node_modules/afas-connect/lib/classes/Profit.js:13:24)
    at Object.<anonymous> (/Users/user/afas-connect-test/node_modules/afas-connect/lib/index.js:4:18)
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
}
```

Package.json:
```
{
  "name": "afas-connect-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "type": "module",
  "dependencies": {
    "afas-connect": "^3.0.3"
  }
}
```

index.js
```
import { Profit } from 'afas-connect';

const bla = new Profit({
  env: 'test',
  envType: 'test',
  token: 'vblasd',
});
```

**Comment by GarbageSlave** [comment]
Hi, thank you for making the issue. I wasn't aware of the CommonJS and ESM conflict with the node-fetch 3 update so I rolled it back to 2.7.0. This should resolve the conflict. Please let me know if this fixed your issue

**Comment by keesvanbemmel** [comment]
Is there a published release of this yet?

**Comment by GarbageSlave** [comment]
Yes, It's in the 3.0.4 release

**Comment by keesvanbemmel** [comment]
Think it's not published yet? https://npm.io/package/afas-connect looks like 3.0.3 still

EDIT: my bad, was looking at wrong package file :)
